# Generated by Django 4.2.5 on 2023-09-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fen',
            name='debiut_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
